### ISSUE TITLE
Creación de oferta/busqueda de trabajo necesita un usuario asociado

### ISSUE THREAD

**Issue by agrojas** [mequieroir/me-quiero-ir-api#1]
Cuando se crea una búsqueda u oferta de trabajo se necesitaría tener un userId asociado para chequear que el tipo de usuario que esta creando esto sea el correcto (compañía o persona)

**Comment by recheconea** [comment]
Ya lo agregue. Ahora voy a trabajar en una validacion de tipo de usuario.
